apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/elyas-gitspace/consumer
  newName: ghcr.io/elyas-gitspace/consumer
  newTag: v0.1.0
- name: ghcr.io/elyas-gitspace/producer
  newTag: latest
