apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: keda-observation
data:
  KAFKA_BROKERS: "redpanda:9092"
  KAFKA_TOPIC: "wikipedia-events"
  KAFKA_GROUP_ID: "wikipedia-consumer-group"
  METRICS_PORT: "9090"
