apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-observation
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/elyas-gitspace/keda-observation.git
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: keda-observation

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
